server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/demo_db
    username: demo_user
    password: demo_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret_key: "mysupermegaduperultralongestsecretkeyforeffectivemobile"
  expiration_time: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs